Components/PurchaseSummaryViewComponent.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Assignment5Webpage.Models;

namespace Assignment5Webpage.Components
{
    public class PurchaseSummaryViewComponent : ViewComponent
    {
        private Cart cart;

        public PurchaseSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }

        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

Views/Shared/BooklistSummary.cshtml
@model Booklist
<!--TABLE-->
   <tr>
            <td class="font-weight-bold">@Model.BookID</td>
            <td><mark>@Model.BookTitle</mark></td>
            <td>@Model.AuthorFirst @Model.AuthorLast</td>
            <td>@Model.Publisher</td>
            <td>@Model.ISBN</td>
            <td>@Model.Classification, @Model.Category</td>
            <td>@Model.PageNum</td>
            <td class="badge badge-pill badge-dark">$@Model.Price</td>
            <td>
                <form id="@Model.BookID" asp-page="/Purchase" method="post">
                    <input type="hidden" asp-for="BookID" />
                    <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
                    <span class="card-text p-1">
                        <button type="submit" class="btn-success btn-sm pull-right" style="float:right">
                            Add to Cart
                        </button>
                    </span>
                </form>

            </td>


   </tr>
 

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Spencer's Bookstore</title>
    <meta name="viewport" content="width=device-width" />
    <!--Connect Bootstrap-->
    <link href="~/css/bootstrap.css" rel="stylesheet" />
    <link href="~/css/main.css" rel="stylesheet" />
    <!--FontAwesome-->
    <script src="https://kit.fontawesome.com/cfcadfc0e5.js" crossorigin="anonymous"></script>

</head>
<body>

    <!--TITLE-->
    <div class="bg-dark text-white text-center p-2">
        <h1>@ViewBag.Title</h1>
    </div>

    <!--SUBTITLE-->
    <div class="text-center">
        <h3 class="bg-dark text-white text-center">@ViewBag.Subtitle</h3>
    </div>

    <div class="bg-dark text-white p-2">
        <div class="container-fluid">
            <div class="row">
                <div class="col navbar-brand"></div>
                <div class="col-6 text-right">
                    <vc:purchase-summary/>
                </div>
            </div>
        </div>
    </div>

    <!--NAVIGATION -
     <div class="topnav">
         <a class="active" asp-controller="Home" asp-action="Index">Home</a>
         <a asp-controller="Home" asp-action="ResturantList">Submit Your Favorite Resturant</a>

     </div>
        -->

    <div>
        @RenderBody()
    </div>


    <br />
    <br />
    <br />

    <!--FOOTER-->
    <footer>
        Spencer's Bookstore &copy; 2021
    </footer>

</body>
</html>