Components/NavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using Assignment5Webpage.Models;
using System.Linq;

namespace Assignment5Webpage.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {

        private iBookRepository repository;

        public NavigationMenuViewComponent (iBookRepository repo)
        {
            repository = repo;
        }

       //method of ViewComponent. This is the navigation Component we plug into shared layout
       public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"]; // ? makes it nullable

            return View(repository.Booklists
                .Select(b => b.Category)
                .Distinct()
                .OrderBy(b => b));
        }

    }
}

//End of Page

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq; //This is like SQL, used for querying.
using System.Threading.Tasks;
using Assignment5Webpage.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Assignment5Webpage.Models.ViewModels;

namespace Assignment5Webpage.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        //Add the repository from the DB to the controller and pass into controller.
        private iBookRepository _repository;

        //Variable to hold the items per page
        public int ItemsPerPage = 5;

        public HomeController(ILogger<HomeController> logger, iBookRepository repository)
        {
            _logger = logger;
            _repository = repository;
        }

        //INDEX VIEW, Insert the data from the DB.
        public IActionResult Index(string category, int pageNum = 1)
        {
            //Tells program which pages and items to grab.
            return View(new ProjectListViewModel
            {
                //Similar to SQL - doing a query. 
                Booklists = _repository.Booklists
                        .Where(b => category == null || b.Category == category)
                        .OrderBy(b => b.BookID)
                        .Skip((pageNum - 1) * ItemsPerPage)
                        .Take(ItemsPerPage)
                    ,
                PagingInfo = new PagingInfo
                {
                    CurrentPage = pageNum,
                    ItemsPerPage = ItemsPerPage, //maybe change name to PageAmt to differentiate
                    TotalNumItems = category == null ?  _repository.Booklists.Count() :
                        _repository.Booklists.Where(b => b.Category == category).Count()

                },

                CurrentCategory = category
              


            });
               
        }

        public IActionResult Create()
        {
            return View();
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Spencer's Bookstore";
    ViewData["SubTitle"] = "A Literary Emporium";
}

<!--Take out the IQueryable Model-->
@model ProjectListViewModel 

<!DOCTYPE html>
<html>

<head>

</head>

<body>

    <br />
    <br />

    <!--IMAGE-->
    <!--# 1 BOOTSTRAP IMPLEMENTED: SHADOWING-->
    <!--# 2 BOOTSTRAP IMPLEMENTED: CONTAINER PADDED BOX-->
    <div class="container">
        <div class="text-center shadow-lg p-3 mb-5 bg-white rounded">
            <a> <img src="img/books.jpeg" class="rounded" /> </a>
            <div class="overlay"></div>
            <br /><br />
        </div>
    </div>
    <br />
    <div class="row p-3">
        <div class="col-2">


            <!--# 3 BOOTSTRAP IMPLEMENTED: HIGHLIGHTS-->
            <h3 class="h3-responsive"><mark>Spencer's Top Picks</mark></h3>
            <vc:navigation-menu /> <!--May need to put this in the _Layout page instead-->
        </div>
   
    <div class="col-10">

        <!--TABLE-->
        <table>
            <tr>
                <!--TABLE HEADERS-->
                <th class="font-weight-bold">Pick</th>
                <th class="font-weight-bold">Title</th>
                <th class="font-weight-bold">Author's Name</th>
                <th class="font-weight-bold">Publisher</th>
                <th class="font-weight-bold">ISBN</th>
                <th class="font-weight-bold">Category</th>
                <th class="font-weight-bold">Page Number</th>
                <th class="font-weight-bold">Price</th>
                <th class="font-weight-bold">Buy</th>


            </tr>

            <!--INSERT DATA INTO TABLE THROUGH LOOP-->
            @foreach (var i in Model.Booklists)
            {
                //Connect to the partial view to display
                <partial name="BooklistSummary" model="i" />
            }

        </table>

    </div>

        <!--This links to the PageLinkTagHelper to declare all of these-->
        <div page-model="@Model.PagingInfo" page-action="Index"
             page-classes-enabled="true" page-class="btn"
             page-class-normal="btn-outline-dark"
             page-class-selected="btn-primary"
             page-url-category="@Model.CurrentCategory"
             class="btn-group pull-right m-2"></div>

</body>

</html>