Pages/Purchase.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Assignment5Webpage.Models;
using Assignment5Webpage.Infrastructure;

namespace Assignment5Webpage.Pages
{
    public class PurchaseModel : PageModel // : means inherit
    {
        private iBookRepository repository;

        //Constructor

        public PurchaseModel(iBookRepository repo, Cart cartService)
        {
            repository = repo;
            Cart = cartService;

        }

        //Properties
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }

        //Methods
        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
        }

        /*/OLD Methods
        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";  //?? means if it's null then x
            Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
        } */

        public IActionResult OnPost(long BookID, string returnUrl)
        {
            Booklist booklist = repository.Booklists.FirstOrDefault(b => b.BookID == BookID);

            //Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();

            Cart.AddItem(booklist, 1);

            //HttpContext.Session.SetJson("cart", Cart);
                
            return RedirectToPage(new { returnUrl = returnUrl });
        }

        public IActionResult OnPostRemove(long BookID, string returnUrl)
        {
            Cart.RemoveLine(Cart.Lines.First(cl => cl.Booklist.BookID == BookID).Booklist);
            return RedirectToPage(new { returnUrl = returnUrl });
        }
    }
}

Pages/Purchase.cshtml
@page

@model Assignment5Webpage.Pages.PurchaseModel

@{
}

<h2>Your Cart</h2>

<table class="table table-bordered table-striped">

    <thead>
        <tr>
            <th>Item</th>
            <th>Quantity</th>
            <th class="text-right">Price</th>
            <th class="text-right">Subtotal</th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var line in Model.Cart.Lines)
        {
            <tr>
                <td class="text-left">@line.Booklist.BookTitle</td>
                <td class="text-center">@line.Quantity</td>
                <td class="text-right">$@line.Booklist.Price.ToString()</td>
                <td class="text-right">$@((line.Quantity * line.Booklist.Price).ToString())</td>
                <td class="text-center">
                    <form asp-page-handler="Remove" method="post">
                        <input type="hidden" name="BookID" value="@line.Booklist.BookID" />
                        <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                        <button type="submit" class="btn btn-sm btn-danger">Remove</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>

    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Total:</td>
            <td class="text-right">$@Model.Cart.ComputeTotalSum().ToString()</td>
        </tr>
    </tfoot>

</table>

<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue Shopping</a>
</div>




<!--Considered an MVVM, Model View View Modeln
    = more self-contained than Model View Controller-->